import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_ui/Navbar";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import { ReactQueryClientProvider } from "./_ui/ReactQueryClientProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const value = cookies().get('token')!;

  return (
    <ReactQueryClientProvider>
    <html lang="en">
      <body className={inter.className}>
        <Navbar value={value}/>
        {children}
        <ToastContainer/>
        </body>
    </html>
    </ReactQueryClientProvider>

  );
}
